// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./Views/Die.js";
import * as $1 from "./Views/Popup.js";
import * as $2 from "./Views/ScoreButton.js";

const manifest = {
  Views: {
    "./Views/Die.ts": $0,
    "./Views/Popup.ts": $1,
    "./Views/ScoreButton.ts": $2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
