// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.js`.

import * as $0 from "./Views/Die.js";
import * as $1 from "./Views/ScoreButton.js";

const manifest = {
  Views: {
    "./Views/Die.js": $0,
    "./Views/ScoreButton.js": $1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
